In [ ]:
import numpy as np
import random

In [ ]:
np.random.seed(0)
X = np.linspace(-np.pi, np.pi, 50).reshape(-1, 1)
Y = np.sin(X)

In [ ]:
X

array([[-3.14159265],
       [-3.01336438],
       [-2.88513611],
       [-2.75690784],
       [-2.62867957],
       [-2.5004513 ],
       [-2.37222302],
       [-2.24399475],
       [-2.11576648],
       [-1.98753821],
       [-1.85930994],
       [-1.73108167],
       [-1.60285339],
       [-1.47462512],
       [-1.34639685],
       [-1.21816858],
       [-1.08994031],
       [-0.96171204],
       [-0.83348377],
       [-0.70525549],
       [-0.57702722],
       [-0.44879895],
       [-0.32057068],
       [-0.19234241],
       [-0.06411414],
       [ 0.06411414],
       [ 0.19234241],
       [ 0.32057068],
       [ 0.44879895],
       [ 0.57702722],
       [ 0.70525549],
       [ 0.83348377],
       [ 0.96171204],
       [ 1.08994031],
       [ 1.21816858],
       [ 1.34639685],
       [ 1.47462512],
       [ 1.60285339],
       [ 1.73108167],
       [ 1.85930994],
       [ 1.98753821],
       [ 2.11576648],
       [ 2.24399475],
       [ 2.37222302],
       [ 2.5004513 ],
       [ 2

In [ ]:
INPUT_SIZE = 1
HIDDEN_SIZE = 5
OUTPUT_SIZE = 1
PARAM_SIZE = INPUT_SIZE * HIDDEN_SIZE + HIDDEN_SIZE + HIDDEN_SIZE * OUTPUT_SIZE + OUTPUT_SIZE

In [ ]:
def decode_parameters(genome):
    w1_end = INPUT_SIZE * HIDDEN_SIZE
    b1_end = w1_end + HIDDEN_SIZE
    w2_end = b1_end + HIDDEN_SIZE * OUTPUT_SIZE
    b2_end = w2_end + OUTPUT_SIZE

    w1 = genome[:w1_end].reshape(INPUT_SIZE, HIDDEN_SIZE)
    b1 = genome[w1_end:b1_end].reshape(1, HIDDEN_SIZE)
    w2 = genome[b1_end:w2_end].reshape(HIDDEN_SIZE, OUTPUT_SIZE)
    b2 = genome[w2_end:b2_end].reshape(1, OUTPUT_SIZE)

    return w1, b1, w2, b2

In [ ]:
def forward(x, genome):
    w1, b1, w2, b2 = decode_parameters(genome)
    hidden = np.tanh(x @ w1 + b1)
    output = hidden @ w2 + b2
    return output

In [ ]:
def fitness(genome):
    pred = forward(X, genome)
    return -np.mean((pred - Y)**2)  # negative because GA maximizes fitness

In [ ]:
POP_SIZE = 50
GENERATIONS = 200
MUTATION_RATE = 0.1

# Initialize population (random weights)
population = [np.random.uniform(-1, 1, PARAM_SIZE) for _ in range(POP_SIZE)]

In [ ]:

def select_parent(fitnesses):
  idx = np.argsort(fitnesses)[-10:] # select top 10 return population[random.choice(idx)]
  return population[random.choice(idx)]
def crossover(p1, p2):
    cut = random.randint(0, PARAM_SIZE - 1)
    child = np.concatenate((p1[:cut], p2[cut:]))
    return child

def mutate(genome):
    for i in range(PARAM_SIZE):
        if random.random() < MUTATION_RATE:
            genome[i] += np.random.normal(0, 0.2)
    return np.clip(genome, -2, 2)

In [ ]:
for gen in range(GENERATIONS):
    fitnesses = np.array([fitness(g) for g in population])
    best_idx = np.argmax(fitnesses)
    best_fit = fitnesses[best_idx]

    new_population = []
    # elitism
    new_population.append(population[best_idx])

    # offspring creation
    while len(new_population) < POP_SIZE:
        p1 = select_parent(fitnesses)
        p2 = select_parent(fitnesses)
        child = crossover(p1, p2)
        child = mutate(child)
        new_population.append(child)

    population = new_population

    if gen % 20 == 0:
        print(f"Gen {gen} → Best fitness: {best_fit:.6f}")

TypeError: object of type 'numpy.int64' has no len()

In [ ]:
best_genome = population[np.argmax([fitness(g) for g in population])]
print("best genom", best_genome)
preds = forward(X, best_genome)

print("\nTraining complete!")
print("Example predictions (x, y_true, y_pred):")
for i in range(0, len(X), 10):
    print(f"x={X[i,0]:.2f}, true={Y[i,0]:.3f}, pred={preds[i,0]:.3f}")

best genom [-0.3475085  -1.47079629 -0.29816901  1.47555525 -0.18474041  1.08543397
 -0.80355474 -0.75391395 -0.9249937  -0.09758689  0.78445175 -0.9888807
  0.50861744  0.87929634  1.84549536 -0.10474623]

Training complete!
Example predictions (x, y_true, y_pred):
x=-3.14, true=-0.000, pred=-0.288
x=-1.86, true=-0.959, pred=-0.850
x=-0.58, true=-0.546, pred=-0.556
x=0.71, true=0.648, pred=0.682
x=1.99, true=0.914, pred=0.781


In [ ]:

fitnesses = np.array([fitness(g) for g in population])
best_genome = population[np.argmax(fitnesses)]


W1_opt, b1_opt, W2_opt, b2_opt = decode_parameters(best_genome)


print("Optimal W1 (input → hidden):\n", W1_opt)
print("Optimal b1 (hidden biases):\n", b1_opt)
print("Optimal W2 (hidden → output):\n", W2_opt)
print("Optimal b2 (output bias):\n", b2_opt)

Optimal W1 (input → hidden):
 [[-0.3475085  -1.47079629 -0.29816901  1.47555525 -0.18474041]]
Optimal b1 (hidden biases):
 [[ 1.08543397 -0.80355474 -0.75391395 -0.9249937  -0.09758689]]
Optimal W2 (hidden → output):
 [[ 0.78445175]
 [-0.9888807 ]
 [ 0.50861744]
 [ 0.87929634]
 [ 1.84549536]]
Optimal b2 (output bias):
 [[-0.10474623]]


In [ ]:
best_parantes = select_parent(fitnesses)
print(best_parantes)

[-0.3475085  -1.51860476 -0.29816901  1.47162434 -0.18474041  1.08543397
 -0.80355474 -0.74589519 -0.98296896 -0.09758689  0.78445175 -0.9888807
  0.50571057  0.87929634  1.81479216 -0.10474623]


In [33]:
def select_parents(fitnesses, population):
    # 1. Sort indexes of fitness scores (ascending) and take top 2
    top2_idx = np.argsort(fitnesses)[-2:]   # <<< UPDATED: was -10, now only top 2

    # 2. Extract the two best individuals
    best_parent = population[top2_idx[-1]]     # Best
    second_parent = population[top2_idx[-2]]   # Second best

    # 3. Print at end
    print("Best parent selected (1st):")
    print(best_parent)

    print("\nSecond best parent selected (2nd):")
    print(second_parent)

    return best_parent, second_parent          # <<< UPDATED: return two vectors


In [36]:

p1, p2 = select_parents(fitnesses, population)

Best parent selected (1st):
[-0.3475085  -1.47079629 -0.29816901  1.47555525 -0.18474041  1.08543397
 -0.80355474 -0.75391395 -0.9249937  -0.09758689  0.78445175 -0.9888807
  0.50861744  0.87929634  1.84549536 -0.10474623]

Second best parent selected (2nd):
[-0.3475085  -1.47079629 -0.29816901  1.47555525 -0.18474041  1.08543397
 -0.80355474 -0.75391395 -0.9249937  -0.09758689  0.78445175 -0.9888807
  0.50861744  0.87929634  1.82205542 -0.10474623]
